version: '2'

services:
  # redis:
  #   image: 'redis:3.2-alpine'
  #   command: redis-server
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - 'redis:/var/lib/redis/data'

  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
  #    - 'redis'
    build: .
    command: bash start.sh
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - '.:/bbatch_files'
    volumes_from:
      - box
  jobs:
    depends_on:
  #    - 'redis'
      - 'website'
    build: .
    command: bash start_jobs.sh
    volumes:
      - '.:/bbatch_files'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box: